import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        foreground: "#dae2fd",
        card: {
          DEFAULT: "#131b2e",
          foreground: "#dae2fd",
        },
        popover: {
          DEFAULT: "#171f33",
          foreground: "#dae2fd",
        },
        primary: {
          DEFAULT: "#4edea3",
          foreground: "#003824",
        },
        secondary: {
          DEFAULT: "#d0bcff",
          foreground: "#3c0091",
        },
        muted: {
          DEFAULT: "#2d3449",
          foreground: "#bbcabf",
        },
        accent: {
          DEFAULT: "#4cd7f6",
          foreground: "#003640",
        },
        destructive: {
          DEFAULT: "#ffb4ab",
          foreground: "#690005",
        },
        border: "rgba(255, 255, 255, 0.05)",
        input: "rgba(255, 255, 255, 0.05)",
        ring: "#4edea3",
        // Custom Stich colors
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-container-high": "#222a3d",
        "on-secondary-fixed": "#23005c",
        "surface-container-lowest": "#060e20",
        "surface-bright": "#31394d",
        "on-primary-container": "#00422b",
        "secondary-container": "#571bc1",
        "surface-container-low": "#131b2e",
        "on-primary-fixed-variant": "#005236",
        "error-container": "#93000a",
        "on-error": "#690005",
        "surface-dim": "#0b1326",
        "tertiary-fixed": "#acedff",
        "surface-tint": "#4edea3",
        "on-tertiary-fixed-variant": "#004e5c",
        "secondary-fixed": "#e9ddff",
        "inverse-on-surface": "#283044",
        "surface-variant": "#2d3449",
        "primary-fixed-dim": "#4edea3",
        "inverse-surface": "#dae2fd",
        "surface": "#0b1326",
        "on-secondary": "#3c0091",
        "outline": "#86948a",
        "on-primary-fixed": "#002113",
        "on-secondary-container": "#c4abff",
        "inverse-primary": "#006c49",
        "surface-container-highest": "#2d3449",
        "on-background": "#dae2fd",
        "on-primary": "#003824",
        "on-tertiary": "#003640",
        "on-surface": "#dae2fd",
        "error": "#ffb4ab",
        "tertiary": "#4cd7f6",
        "on-tertiary-fixed": "#001f26",
        "surface-container": "#171f33",
        "on-tertiary-container": "#003f4b",
        "primary-fixed": "#6ffbbe",
        "primary-container": "#10b981",
        "outline-variant": "#3c4a42",
        "secondary-fixed-dim": "#d0bcff",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#00b2d0",
        "on-secondary-fixed-variant": "#5516be",
        "on-surface-variant": "#bbcabf",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        gutter: "24px",
        "stack-lg": "32px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
